In [94]:
import torch
import numpy as np

In [2]:
#x=torch.empty(1)

In [20]:
#x

In [8]:
#x=torch.empty(3)

In [21]:
#x

In [10]:
#x=torch.empty(2,3)

In [17]:
#x

In [32]:
#x=torch.empty(2, 2, 3)

In [33]:
#x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [34]:
#x=torch.empty(2, 2, 2, 3)

In [35]:
#x

tensor([[[[1.3540e+28, 6.8523e-43, 1.5273e+28],
          [6.8523e-43, 1.3540e+28, 6.8523e-43]],

         [[1.5273e+28, 6.8523e-43, 1.3540e+28],
          [6.8523e-43, 1.3559e+28, 6.8523e-43]]],


        [[[1.4304e+28, 6.8523e-43, 1.3559e+28],
          [6.8523e-43, 1.8602e+37, 6.8523e-43]],

         [[1.8602e+37, 6.8523e-43, 1.4638e+28],
          [6.8523e-43, 1.5272e+28, 6.8523e-43]]]])

In [36]:
#x=torch.rand(2, 2)

In [37]:
#x

tensor([[0.1055, 0.5556],
        [0.3851, 0.9272]])

In [38]:
#x=torch.zeros(2, 2)

In [39]:
#x

tensor([[0., 0.],
        [0., 0.]])

In [40]:
#x=torch.ones(2, 2)

In [41]:
#x

tensor([[1., 1.],
        [1., 1.]])

In [42]:
#x.dtype

torch.float32

In [43]:
#x=torch.ones(2, 2,dtype=torch.float16)

In [45]:
#x.size()

torch.Size([2, 2])

In [46]:
#x=torch.tensor([2.5,0.1])

In [47]:
#x

tensor([2.5000, 0.1000])

In [48]:
#x=torch.rand(2, 2)

In [49]:
#y=torch.rand(2, 2)

In [50]:
#x

tensor([[0.8744, 0.7041],
        [0.3786, 0.4668]])

In [51]:
#y

tensor([[0.6752, 0.2965],
        [0.1286, 0.6637]])

In [52]:
#z=x+y

In [53]:
#z

tensor([[1.5496, 1.0006],
        [0.5072, 1.1305]])

In [54]:
#x=torch.rand(2, 2)
#y=torch.rand(2, 2)

In [55]:
#x

tensor([[0.2029, 0.9884],
        [0.3865, 0.4573]])

In [56]:
#y

tensor([[0.6978, 0.5462],
        [0.6591, 0.6291]])

In [57]:
#z=x+y

In [58]:
#z=torch.add(x,y)

In [59]:
#z

tensor([[0.9006, 1.5346],
        [1.0456, 1.0864]])

In [60]:
#x=torch.rand(2, 2)
#y=torch.rand(2, 2)

In [61]:
#y.add_(x)

tensor([[1.2432, 0.6435],
        [1.5815, 0.6281]])

In [62]:
#x=torch.rand(2, 2)
#y=torch.rand(2, 2)

In [63]:
#z=x-y

In [64]:
#z=torch.sub(x,y)

In [65]:
#z

tensor([[-0.5393,  0.1898],
        [ 0.2070, -0.3393]])

In [66]:
#x=torch.rand(2, 2)
#y=torch.rand(2, 2)

In [67]:
#z=x*y

In [68]:
#z=torch.mul(x,y)

In [69]:
#z

tensor([[0.0083, 0.8238],
        [0.2706, 0.1289]])

In [70]:
#x=torch.rand(5, 3)

In [71]:
#x

tensor([[0.0045, 0.9861, 0.5811],
        [0.4425, 0.4724, 0.2732],
        [0.8262, 0.4020, 0.4306],
        [0.2180, 0.2252, 0.1709],
        [0.7968, 0.5875, 0.4106]])

In [72]:
#x=torch.rand(5, 3)

In [74]:
#x

tensor([[0.0805, 0.3028, 0.1901],
        [0.6072, 0.3579, 0.3208],
        [0.0171, 0.3379, 0.4857],
        [0.8093, 0.0123, 0.3911],
        [0.0686, 0.8011, 0.3661]])

In [73]:
#x[:,0]

tensor([0.0805, 0.6072, 0.0171, 0.8093, 0.0686])

In [75]:
#x=torch.rand(5, 3)

In [76]:
#x

tensor([[0.4740, 0.0791, 0.9570],
        [0.9054, 0.8864, 0.0925],
        [0.6521, 0.3277, 0.8276],
        [0.6617, 0.3055, 0.1899],
        [0.4359, 0.6497, 0.9754]])

In [77]:
#x[1,:]

tensor([0.9054, 0.8864, 0.0925])

In [78]:
#x[1,1]

tensor(0.8864)

In [79]:
#x[1,1].item()

0.886437177658081

In [89]:
x=torch.rand(4, 4)

In [90]:
x

tensor([[0.7694, 0.4632, 0.9593, 0.1058],
        [0.9139, 0.2957, 0.6260, 0.6255],
        [0.3720, 0.3392, 0.4365, 0.4678],
        [0.7659, 0.3883, 0.5694, 0.0056]])

In [85]:
#y=x.view(16)

In [86]:
#y

tensor([0.9357, 0.7414, 0.2501, 0.7354, 0.1493, 0.2424, 0.3127, 0.2249, 0.5796,
        0.6371, 0.5556, 0.2329, 0.7397, 0.9336, 0.6828, 0.0478])

In [91]:
#y=x.view(-1,8)

In [92]:
#y

tensor([[0.7694, 0.4632, 0.9593, 0.1058, 0.9139, 0.2957, 0.6260, 0.6255],
        [0.3720, 0.3392, 0.4365, 0.4678, 0.7659, 0.3883, 0.5694, 0.0056]])

In [93]:
#y.size()

torch.Size([2, 8])

In [95]:
#a=torch.ones(5)

In [96]:
#a

tensor([1., 1., 1., 1., 1.])

In [97]:
#b=a.numpy()

In [98]:
#b

array([1., 1., 1., 1., 1.], dtype=float32)

In [99]:
#type(b)

numpy.ndarray

In [100]:
#a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [101]:
#b

array([2., 2., 2., 2., 2.], dtype=float32)

In [102]:
#a=np.ones(5)

In [103]:
#a

array([1., 1., 1., 1., 1.])

In [104]:
#b=torch.from_numpy(a)

In [105]:
#b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [106]:
#a+=1

In [107]:
#a

array([2., 2., 2., 2., 2.])

In [108]:
#b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [113]:
x=torch.ones(5, requires_grad=True)

In [114]:
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)